failed echo

diff --git a/.github/workflows/prerelease.yml b/.github/workflows/prerelease.yml
--- a/.github/workflows/prerelease.yml
+++ b/.github/workflows/prerelease.yml
@@ -31,12 +31,15 @@ jobs:
       - name: Generate artifact
         run: |
           ./gradlew -PideProfileName=2023.3 :plugin-toolkit:intellij:buildPlugin
+          if $? -ne 0; then
+            echo "Failed"
+
           
           #./gradlew -PideProfileName=${{ matrix.supported_versions }} :plugin-toolkit:intellij:buildPlugin
       - name: Clear disk space
         run: |
           echo $(df -h)
-          
+
 #      - name:  Upload artifact
 #        uses: actions/upload-artifact@v4
 #        with:
